export { default as Home } from './home/Home'
export { default as Shop } from './shop/Shop'
export { default as SingleProductDetail } from './shop/SingleProductDetail'
export { default as Cart } from './cart/Cart'
export { default as Login } from './auth/Login'
export { default as Register } from './auth/Register'
export { default as NotFound } from './notFound/NotFound'