export { default as Home } from './Home'
export { default as Shop } from './Shop'
export { default as SingleProductDetail } from './SingleProductDetail'
export { default as Cart } from './Cart'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as NotFound } from './NotFound'